apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: prod
spec:
  selector:
    app: cart
    version: blue  # <<< starts pointing to blue version
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
