apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: prod
spec:
  selector:
    app: frontend
    version: blue
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # <- IMPORTANT: exposes port 30080 on each Node