apiVersion: batch/v1
kind: Job
metadata:
  name: uat-cleanup
  namespace: uat
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - /bin/bash
            - -c
            - |
              kubectl delete all --all -n uat
              kubectl delete configmap env-config -n uat
      restartPolicy: Never