# UAT Deployments and Services

# Frontend Deployment (UAT)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <your-ecr-repo>/frontend:uat
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: env-config
              mountPath: /app/public/env-config.js
              subPath: env-config.js
      volumes:
        - name: env-config
          configMap:
            name: env-config
---
# Cart Deployment (UAT)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart
          image: <your-ecr-repo>/cart-service:uat
          ports:
            - containerPort: 3002
---
# Order Deployment (UAT)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order
          image: <your-ecr-repo>/order-service:uat
          ports:
            - containerPort: 3001
---
# Product Deployment (UAT)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product
          image: <your-ecr-repo>/product-service:uat
          ports:
            - containerPort: 3003