apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-blue
  namespace: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
      version: blue
  template:
    metadata:
      labels:
        app: order
        version: blue
    spec:
      containers:
      - name: order
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/order-service:${IMAGE_TAG}
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "${DB_HOST}"
        - name: DB_USER
          value: "${DB_USER}"
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
        - name: DB_NAME
          value: "orderdb"
        - name: PORT
          value: "3001"
