apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-green
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
      version: green
  template:
    metadata:
      labels:
        app: cart-service
        version: green
    spec:
      containers:
        - name: cart
          image: <your-ecr-repo>/cart-service:green
          ports:
            - containerPort: 3002