apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-green
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: green
  template:
    metadata:
      labels:
        app: order-service
        version: green
    spec:
      containers:
        - name: order
          image: <your-ecr-repo>/order-service:green
          ports:
            - containerPort: 3002