# Cart Blue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-blue
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
      version: blue
  template:
    metadata:
      labels:
        app: cart-service
        version: blue
    spec:
      containers:
        - name: cart
          image: <your-ecr-repo>/cart-service:blue
          ports:
            - containerPort: 3002