# Order Blue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-blue
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: blue
  template:
    metadata:
      labels:
        app: order-service
        version: blue
    spec:
      containers:
        - name: order
          image: <your-ecr-repo>/order-service:blue
          ports:
            - containerPort: 3001