name: Switch Service to Green

on:
  repository_dispatch:
    types: [switch-service-to-green]
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Base service name (frontend, cart-service, etc.)'
        required: true
        type: string
      version:
        description: 'Image tag version to deploy (e.g., 1.0.0-green, 1.0.0-stable)'
        required: true
        type: string

jobs:
  deploy-service:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Service Name and VERSION
        id: set-vars
        run: |
          if [ -n "${{ github.event.client_payload.service }}" ]; then
            SERVICE_NAME="${{ github.event.client_payload.service }}"
            VERSION="${{ github.event.client_payload.version }}"
          else
            SERVICE_NAME="${{ github.event.inputs.service_name }}"
            VERSION="${{ github.event.inputs.version }}"
          fi

          echo "Service: $SERVICE_NAME"
          echo "Version: $VERSION"

          # Determine Namespace properly
          NAMESPACE="prod"

          echo "Target namespace: $NAMESPACE"

          echo "service_name=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout Infra Repo
        uses: actions/checkout@v4
        with:
          path: Infra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_ACCOUNT_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Re-tag RC-1 Build as Green
        run: |
          SERVICE_NAME="${{ steps.set-vars.outputs.service_name }}"
          NAMESPACE="${{ steps.set-vars.outputs.namespace }}"
          VERSION="${{ steps.set-vars.outputs.version }}"

          # Extract base version (remove '-green' suffix)
          BASE_VERSION="${VERSION%-green}"

          REPO_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_ACCOUNT_REGION }}.amazonaws.com/$SERVICE_NAME

          RC_TAG="$BASE_VERSION-rc-1"
          GREEN_TAG="$BASE_VERSION-green"

          echo "📦 Repo: $REPO_URI"
          echo "🔍 Retagging $RC_TAG ➔ $GREEN_TAG"

          echo "⏳ Attempting to pull RC-1 image: $RC_TAG"
          if docker pull $REPO_URI:$RC_TAG; then
            echo "✅ Successfully pulled RC-1 image: $RC_TAG"
          else
            echo "❌ Failed to pull RC-1 image: $RC_TAG"
            echo "🚫 Cannot proceed with re-tagging."
            exit 1
          fi

          echo "🏷️ Re-tagging image as $GREEN_TAG"
          docker tag $REPO_URI:$RC_TAG $REPO_URI:$GREEN_TAG

          echo "🚀 Pushing Green tag to ECR..."
          docker push $REPO_URI:$GREEN_TAG

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_ACCOUNT_REGION }}

      - name: Deploy Service
        run: |
          SERVICE_NAME="${{ steps.set-vars.outputs.service_name }}"
          VERSION="${{ steps.set-vars.outputs.version }}"

          echo "🌎 Deploying service: $SERVICE_NAME as color: green with version: $VERSION into prod"

          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          export AWS_REGION=${{ secrets.AWS_ACCOUNT_REGION }}
          export REDIS_URL=${{ secrets.REDIS_URL }}
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_USER=${{ secrets.DB_USER }}
          export COLOR=green
          export IMAGE_TAG=$VERSION

          # Path to your dynamic deployment template
          TEMPLATE_FILE="Infra/k8s/prod/deployments/${SERVICE_NAME}-deployment.yaml"

          if [ ! -f "$TEMPLATE_FILE" ]; then
            echo "❌ Template file not found: $TEMPLATE_FILE"
            exit 1
          fi

          # Render and apply
          envsubst < "$TEMPLATE_FILE" | kubectl apply -f -
          
          echo "✅ Deployment applied successfully!"

      - name: Wait for Green Deployment to be Ready
        run: |
          SERVICE="${{ steps.set-vars.outputs.service_name }}"
          NAMESPACE="${{ steps.set-vars.outputs.namespace }}"

          # Determine the real service resource name
          if [ "$SERVICE" = "frontend" ]; then
            SERVICE_RESOURCE_NAME="frontend-service"
          else
            SERVICE_RESOURCE_NAME="$SERVICE"
          fi

          echo "⏳ Waiting for Green Deployment: ${SERVICE_RESOURCE_NAME}-green in ${NAMESPACE}"

          kubectl rollout status deployment/${SERVICE_RESOURCE_NAME}-green -n $NAMESPACE --timeout=300s

      - name: Patch Service to Route to Green
        run: |
          SERVICE="${{ steps.set-vars.outputs.service_name }}"
          NAMESPACE="${{ steps.set-vars.outputs.namespace }}"

          # Determine the real service resource name
          if [ "$SERVICE" = "frontend" ]; then
            SERVICE_RESOURCE_NAME="frontend-service"
          else
            SERVICE_RESOURCE_NAME="$SERVICE"
          fi

          echo "🔵 Patching Service ${SERVICE_RESOURCE_NAME} to point to Green pods..."

          kubectl patch service ${SERVICE_RESOURCE_NAME} -n $NAMESPACE -p '{"spec":{"selector":{"app":"'"$SERVICE"'","version":"green"}}}'

      - name: Verify Service is Now Routing to Green Pods
        run: |
          SERVICE="${{ steps.set-vars.outputs.service_name }}"
          NAMESPACE="${{ steps.set-vars.outputs.namespace }}"

          # Determine the real service resource name
          if [ "$SERVICE" = "frontend" ]; then
            SERVICE_RESOURCE_NAME="frontend-service"
          else
            SERVICE_RESOURCE_NAME="$SERVICE"
          fi

          echo "🔍 Checking Service selector after patch..."
          kubectl get service ${SERVICE_RESOURCE_NAME} -n $NAMESPACE -o jsonpath='{.spec.selector}'

          echo "✅ Switched traffic to Green! Blue deployment still exists for rollback if needed. Green switch completed successfully for service: $SERVICE"
